[[questions]]
type = "ShortAnswer"
prompt.prompt = "What is the decimal equivalent of 0b100 (type a number as the answer)?"
answer.answer = "4"
context = "1* 2^2 + 0 * 2^0 + 0 * 2^0"

[[questions]]
type = "ShortAnswer"
prompt.prompt = "What is the decimal equivalent of 0b1011 (type a number as the answer)?"
answer.answer = "11"
context = "1 * 2^3 + 0 * 2^2 + 1 * 2^1 + 1 * 2^0"

[[questions]]
type = "ShortAnswer"
prompt.prompt = "What is the decimal equivalent of 0b10000 (type a number as the answer)?"
answer.answer = "16"
context = "1 * 2^4 + 0 * 2^3 + 0 * 2^2 + 0 * 2^1 + 0 * 2^0"

[[questions]]
type = "ShortAnswer"
prompt.prompt = "What is the decimal equivalent of 0b11001 (type a number as the answer)?"
answer.answer = "25"
context = "1 * 2^4 + 1 * 2^3 + 0 * 2^2 + 0 * 2^1 + 1 * 2^0"